### ISSUE TITLE
Bing doesn't know where Italy is

### ISSUE THREAD

**Issue by DWAK-ATTK** [dotnet-presentations/dotnetconf2019#1]
On the local events page, https://www.dotnetconf.net/local-events, Bing places Italy in southern California, USA. 

Perhaps in addition to launching dotnet core 3.0, Microsoft is going to demonstrate the ability to move countries around the globe? :)

**Comment by zacharycmontoya** [comment]
I noticed the same thing before, but it looks like the issue has been fixed now.

**Comment by jongalloway** [comment]
Fixed - the issue was that the province had been left blank, so our geocoding logic was finding a Caserta Street in California. I updated the record to include the province.
