### ISSUE TITLE
Update website to link this repo instead

### ISSUE THREAD

**Issue by iamalexmang** [dotnet-presentations/dotnetconf2019#2]
Hi!
Please know that the dotnetconf.com website currently redirects to the incorrect repo (namely dotnetconf2018) on the 'Take a look at our "Event-in-a-box" on GitHub to help you' URL.
That's on the https://www.dotnetconf.net/local-events webpage.
Hope this helps.

**Comment by WiredUK** [comment]
The link does point to the correct place.

**Comment by iamalexmang** [comment]
I does now. :-)

**Comment by WiredUK** [comment]
Yeah, I was just saying so you could close the issue rather than wait for someone to do it for you.

**Comment by iamalexmang** [comment]
Yeah, that's fair. Would have been appropriate though for whoever fixed the thing to close the issue or at least leave a comment here, though.

**Comment by WiredUK** [comment]
They may have fixed it without seeing this issue, though I'm sure they appreciate the heads up.
