### ISSUE TITLE
Building real-time image classifiers for mobile apps with Azure Custom Vision is missing

### ISSUE THREAD

**Issue by hmheng** [dotnet-presentations/dotnetconf2019#31]
Building real-time image classifiers for mobile apps with Azure Custom Vision slide and video on channel 9 is missing

**Comment by icebeam7** [comment]
Hi. I sent the [PR ](https://github.com/dotnet-presentations/dotnetconf2019/pull/22)with the slides, in the meantime you can download them from [here](https://github.com/icebeam7/dotnetconf2019/blob/master/Technical/Building%20a%20mobile%20image%20classifier%20with%20Custom%20Vision.pdf).

Video is available on [YouTube](https://www.youtube.com/watch?list=PLReL099Y5nRd04p81Q7p5TtyjCrj9tz1t&v=4oKcLkfYLUo) and [Channel9](https://channel9.msdn.com/Events/dotnetConf/NET-Conf-2019/B315).

Finally, you can get the source code of the demo [here](https://github.com/icebeam7/MobileClassifierDemo).

Feel free to reach out with any questions that you may encounter 😄
