### ISSUE TITLE
Tips and Tricks on Moving to .NET Core .pptx seems to have wrong presentation

### ISSUE THREAD

**Issue by Daniel-Steiner** [dotnet-presentations/dotnetconf2019#4]
@BethMassi 
the file does contain a presentation about "What's new with F#" and not presentation about moving to .NET Core

**Comment by BethMassi** [comment]
Sorry about that. Fixed the file name.

**Comment by payini** [comment]
I just downloaded the presentation again, and it seems it still shows "What's new with F#"

**Comment by BethMassi** [comment]
Ooops how about now? Binary files are tricky in GitHub. I changed the filename to match the presentation content.

**Comment by payini** [comment]
Yep, it's working now. Thank you!

The issue now though is that Tips and Tricks on Moving to .NET Core is missing. I created Issue #28 for that.
